react-financial/react-financial-charts

.circleci/config.yml
.github/workflows/main.yml
README.md
package-lock.json
packages/react-financial-charts/package.json
packages/react-financial-charts/src/indicator/index.ts
packages/react-financial-charts/src/tooltip/HoverTooltip.tsx

Until github actions are enabled we're using circleci.
Fixed lint.
Adding Roadmap to README.

build: adding circleci config

---

.circleci/config.yml
.github/lock.yml
.github/stale.yml
lerna.json
package.json
packages/react-financial-charts-examples/package.json
packages/react-financial-charts/package.json

Current thinking is that the version command is done manually to ensure
the versioning and changelogs are correct. Publishing will be done by the
CI.

build: adding configuration for versioning and publishing

---

lerna.json
package.json

Changing the branch you can version from to release.

build: allow versioning from local release branch

---

.circleci/config.yml
package.json

The npm set never works for publishing, trying to echo settings
instead.

build: fixing npmrc settings for deploy

---

packages/charts/CHANGELOG.md
packages/charts/README.md
packages/charts/package.json

Adding static readme to package.
Correcting github url.

fix: adding missing readme from package

---

lerna.json

Bit of difficulty with lerna, for now release will be done on master.

fix: specifing release branch as master

---

.github/issue_template.md
.github/pull_request_template.md

Adding issue and pull request templates.

docs: adding github templates

---

README.md
package-lock.json
package.json

npm scoring includes the number of badges in your readme, adding the
minimum number; which is 4.

chore(readme): adding badges to readme

---

.circleci/config.yml
packages/charts/src/series/BollingerSeries.tsx
packages/charts/src/series/OHLCSeries.tsx
packages/charts/src/tooltip/BollingerBandTooltip.tsx
packages/stories/src/indicators/bollingerBand/bollingerIndicator.tsx
packages/stories/src/indicators/bollingerBand/index.stories.tsx
packages/stories/src/series/ohlc/basicOHLCSeries.tsx
packages/stories/src/series/ohlc/index.stories.tsx

Bollinger Band & OHLC series

---

packages/charts/src/tooltip/OHLCTooltip.tsx

Add option to display the last item as default OHLC, fix issue https://github.com/rrag/react-stockcharts/issues/717

Add option to display the last item as default OHLC

---

packages/charts/src/indicator/change.ts
packages/charts/src/indicator/elderRay.ts
packages/charts/src/series/GroupedBarSeries.tsx
packages/charts/src/series/KagiSeries.tsx
packages/charts/src/series/LineSeries.tsx
packages/charts/src/series/MACDSeries.tsx
packages/stories/src/indicators/atr/atrIndicator.tsx
packages/stories/src/indicators/atr/index.stories.tsx
packages/stories/src/indicators/elderRay/elderRayIndicator.tsx
packages/stories/src/indicators/elderRay/index.stories.tsx
packages/stories/src/indicators/forceIndex/forceIndicator.tsx
packages/stories/src/indicators/forceIndex/index.stories.tsx
packages/stories/src/indicators/rsi/rsiIndicator.tsx

Some more props corrected.
Added ATR, Force Index and Elder Ray stories.

fix(props): correcting more props

---

package-lock.json
package.json
packages/charts/src/ChartCanvas.tsx
packages/charts/src/EventCapture.tsx
packages/stories/.storybook/webpack.config.js
packages/stories/src/features/Intro.stories.mdx
packages/stories/src/features/interaction/index.stories.tsx
packages/stories/src/features/interaction/interaction.tsx
packages/stories/src/features/stockChart.tsx
packages/stories/src/series/area/basicAreaSeries.tsx
packages/stories/src/series/bar/basicBarSeries.tsx
packages/stories/src/series/candlestick/basicCandlestick.tsx
packages/stories/src/series/heikinAshi/basicHeikinAshiSeries.tsx
packages/stories/src/series/kagi/basicKagiSeries.tsx
packages/stories/src/series/line/basicLineSeries.tsx
packages/stories/src/series/pointAndFigure/basicPointAndFigureSeries.tsx
packages/stories/src/series/renko/basicRenkoSeries.tsx

Adding stories for interaction

---

.github/lock.yml
.github/stale.yml

7 days till stale, 7 more to close, 7 more to lock.

chore(github): updating stale and lock settings

---

packages/stories/src/indicators/atr/index.stories.tsx
packages/stories/src/indicators/bollingerBand/index.stories.tsx
packages/stories/src/indicators/elderRay/index.stories.tsx
packages/stories/src/indicators/ema/index.stories.tsx
packages/stories/src/indicators/forceIndex/index.stories.tsx
packages/stories/src/indicators/macd/index.stories.tsx
packages/stories/src/indicators/rsi/index.stories.tsx
packages/stories/src/indicators/sar/index.stories.tsx
packages/stories/tsconfig.json
packages/stories/tslint.yaml

Title needs to be listed as the first property for storybook to compile

fix(docs): storybook requires an ordering to properties

---

.github/stale.yml
package-lock.json
packages/charts/src/coordinates/EdgeCoordinateV3.tsx
packages/charts/src/coordinates/EdgeIndicator.tsx
packages/charts/src/coordinates/MouseCoordinateY.tsx
packages/stories/src/features/coordinates/coordinates.tsx
packages/stories/src/features/coordinates/index.stories.tsx

Fix for edge coordinates

---

packages/charts/src/CanvasContainer.tsx
packages/charts/src/ChartCanvas.tsx
packages/charts/src/algorithm/index.ts
packages/charts/src/annotation/Annotate.tsx
packages/charts/src/axes/Axis.tsx
packages/charts/src/coordinates/CrossHairCursor.tsx
packages/charts/src/coordinates/Cursor.tsx
packages/charts/src/coordinates/EdgeCoordinateV3.tsx
packages/charts/src/coordinates/MouseCoordinateY.tsx
packages/charts/src/interactive/Brush.tsx
packages/charts/src/interactive/components/InteractiveYCoordinate.tsx
packages/charts/src/interactive/components/StraightLine.tsx
packages/charts/src/interactive/wrapper/EachInteractiveYCoordinate.tsx
packages/charts/src/scale/discontinuousTimeScaleProvider.ts
packages/charts/src/scale/evaluator.ts
packages/charts/src/scale/financeDiscontinuousScale.ts
packages/charts/src/series/LineSeries.tsx
packages/charts/src/series/StraightLine.tsx
packages/charts/src/utils/strokeDasharray.ts
packages/stories/src/features/stockChart.tsx

Fixes for line dash and edge coordinates

---

.circleci/config.yml

Adding fossa to analyze and report on any license issues.

build: running fossa command after build

---

.circleci/config.yml

build: correcting fossa working directory

---

README.md

The badge should show any license issues.

docs: adding fossa badge to readme

---

.vscode/launch.json
packages/charts/src/ChartCanvas.tsx
packages/charts/src/EventCapture.tsx
packages/stories/package.json

Scroll direction is now natural which is the default for touch devices.
Closes #57

fix(charts): reversing scroll direction on touch devices and trackpads

---

package-lock.json

It seems dependabot didn't update the package lock correctly, manually fixing.
Closes #131

fix(docs): the package-lock.json is incorrect

---

package-lock.json

gh-pages isn't updating, hopefully this will kick it off.

docs: regenerating package-lock

---

package-lock.json

Dependabot doesn't work too well with hoisting, correcting deps.

build: correcting package-lock so that dependencies are hoisted

---

package-lock.json

d3-scale was on the wrong version.

docs: fixing dependencies needed for generating docs

---

packages/charts/src/interactive/ZoomButtons.tsx
packages/stories/src/features/FullCanvas.stories.tsx
packages/stories/src/features/stockChart.tsx

Using circles instead of rects.
Adding zoom buttons to stories.

feat(charts): updated zoom buttons styling

---

package-lock.json

docs: bug in core-js-compat, so I'm fixing the version

---

packages/charts/package.json
packages/charts/src/axes/XAxis.tsx

Fix source maps

---

.gitignore
.vscode/launch.json
package-lock.json
package.json
packages/charts/src/tooltip/BollingerBandTooltip.tsx
packages/charts/src/tooltip/GroupTooltip.tsx
packages/charts/src/tooltip/MACDTooltip.tsx
packages/charts/src/tooltip/MovingAverageTooltip.tsx
packages/charts/src/tooltip/RSITooltip.tsx
packages/charts/src/tooltip/StochasticTooltip.tsx
packages/stories/src/indicators/atr/atrIndicator.tsx
packages/stories/src/indicators/bollingerBand/bollingerIndicator.tsx
packages/stories/src/indicators/elderRay/elderRayIndicator.tsx
packages/stories/src/indicators/ema/emaIndicator.tsx
packages/stories/src/indicators/forceIndex/forceIndicator.tsx
packages/stories/src/indicators/macd/macdIndicator.tsx
packages/stories/src/indicators/rsi/rsiIndicator.tsx
packages/stories/src/indicators/sar/sarIndicator.tsx
packages/stories/src/series/area/basicAreaSeries.tsx
packages/stories/src/series/bar/basicBarSeries.tsx
packages/stories/src/series/baseline/basicBaselineSeries.tsx
packages/stories/src/series/candlestick/basicCandlestick.tsx
packages/stories/src/series/heikinAshi/basicHeikinAshiSeries.tsx
packages/stories/src/series/kagi/basicKagiSeries.tsx
packages/stories/src/series/line/basicLineSeries.tsx
packages/stories/src/series/ohlc/basicOHLCSeries.tsx
packages/stories/src/series/pointAndFigure/basicPointAndFigureSeries.tsx
packages/stories/src/series/renko/basicRenkoSeries.tsx

displayInit & lerna bump

---

packages/stories/src/series/area/basicAreaSeries.tsx
packages/stories/src/series/area/index.stories.tsx
packages/stories/src/series/bar/basicBarSeries.tsx
packages/stories/src/series/bar/index.stories.tsx
packages/stories/src/series/baseline/basicBaselineSeries.tsx
packages/stories/src/series/baseline/index.stories.tsx
packages/stories/src/series/candlestick/basicCandlestick.tsx
packages/stories/src/series/candlestick/index.stories.tsx
packages/stories/src/series/heikinAshi/basicHeikinAshiSeries.tsx
packages/stories/src/series/heikinAshi/index.stories.tsx
packages/stories/src/series/kagi/basicKagiSeries.tsx
packages/stories/src/series/kagi/index.stories.tsx
packages/stories/src/series/line/basicLineSeries.tsx
packages/stories/src/series/line/index.stories.tsx
packages/stories/src/series/ohlc/basicOHLCSeries.tsx
packages/stories/src/series/ohlc/index.stories.tsx
packages/stories/src/series/pointAndFigure/basicPointAndFigureSeries.tsx
packages/stories/src/series/pointAndFigure/index.stories.tsx
packages/stories/src/series/renko/basicRenkoSeries.tsx
packages/stories/src/series/renko/index.stories.tsx

chore(stories): adding daily and intraday examples to series

---

package.json

docs: making sure packages are build before docs run

---

packages/annotations/src/Annotate.tsx
packages/annotations/src/BackgroundText.tsx
packages/annotations/src/BarAnnotation.tsx
packages/annotations/src/Label.tsx
packages/annotations/src/LabelAnnotation.tsx
packages/annotations/src/SvgPathAnnotation.tsx

Checking code for issues, and prop types.

chore(annotations): adding types, tidying code

---

packages/tooltip/src/SingleValueTooltip.tsx

any seems to be the easiest to use.

fix(tooltip): removing generic from SingleValueTooltip

---

packages/stories/src/indicators/compare/CompareIndicator.tsx

docs: correcting compare axis

---

packages/core/src/utils/ChartDataUtil.ts

Checking props for id to allow external components as mentioned in #417.

fix(core): using type guard to check type of canvas children

---

packages/core/src/utils/ChartDataUtil.ts
packages/stories/src/features/axis/Axis.tsx

Checking for null children for the chart.

fix(core): children can be undefined or null

---

packages/coordinates/src/EdgeIndicator.tsx

We don't always have a value to draw.

fix(coordinates): EdgeIndicator yAccessor should allow undefined

---

packages/interactive/src/components/HoverTextNearMouse.tsx
packages/series/src/BarSeries.tsx
packages/series/src/MACDSeries.tsx
packages/series/src/StackedBarSeries.tsx

Interactive fixes

---

packages/axes/src/XAxis.tsx
packages/axes/src/YAxis.tsx
packages/core/src/utils/barWidth.ts
packages/indicators/src/indicator/algorithm.ts
packages/indicators/src/indicator/index.ts
packages/stories/src/features/scales/Scales.tsx

Continuous scale bars

---

packages/core/src/ChartCanvas.tsx

This allows a bit more flexibity in the api.

feat(core): replaced onLoadMore with onLoadBefore & onLoadAfter

---

README.md
package-lock.json
packages/axes/package.json
packages/coordinates/package.json
packages/core/package.json
packages/indicators/package.json
packages/interactive/package.json
packages/scales/package.json
packages/series/package.json
packages/stories/package.json
packages/tooltip/package.json

Deps rebuild

---

packages/scales/src/discontinuousTimeScaleProvider.ts

fix: indexAccessor(d) on discontinuousTimeScaleProvider

---

packages/stories/src/features/annotated/Annotated.tsx
packages/stories/src/features/annotated/index.stories.tsx

Highlighting mondays.
Example for #461

chore(stories): adding annotate example

---

.github/codeql-config.yml
.github/workflows/codeql-analysis.yml
packages/series/src/AlternatingFillAreaSeries.tsx
packages/series/src/AreaOnlySeries.tsx
packages/series/src/AreaSeries.tsx

- adding connectNulls to area series

Area nulls

---

packages/annotations/src/LabelAnnotation.tsx
packages/annotations/src/SvgPathAnnotation.tsx
packages/stories/src/features/annotated/Annotated.tsx
packages/stories/src/features/annotated/index.stories.tsx

It was a pain to build a custom path, translate it instead.

fix(annotations): fixing svg path annotation

---

packages/series/src/AreaOnlySeries.tsx
packages/series/src/AreaSeries.tsx

This would allow the creation of a gradient for the fillStyle option of the AreaSeries
This is a quick hack for #518

Provide a `fillStyle` factory option

---

packages/annotations/package.json
packages/axes/package.json
packages/charts/package.json
packages/coordinates/package.json
packages/core/jest.config.js
packages/core/package.json
packages/indicators/package.json
packages/interactive/package.json
packages/scales/package.json
packages/series/package.json
packages/tooltip/package.json
packages/utils/package.json

Specifies that the library contains all es modules.
Relates to #520

fix: adding module to type property in package.json

---

packages/annotations/README.md
packages/axes/README.md
packages/coordinates/README.md
packages/core/README.md
packages/indicators/README.md
packages/interactive/README.md
packages/scales/README.md
packages/series/README.md
packages/tooltip/README.md
packages/utils/README.md

Fix financial typo in readme files

---

.github/workflows/gh-pages.yml

build(github): fixing version of node for storybook

---

package-lock.json
package.json

chore(deps): bump typescript from 4.2.2 to 4.9.5
